import type { Metadata } from "next";

// Static visual mockup — not linked from navigation, excluded from indexing.
// Generated by scripts/build-design-mockups.mjs from design-mockups/navrh-1-tatry.html.
export const metadata: Metadata = {
  title: "Návrh 1 – Tatranský horizont | Q4.sk návrh",
  robots: { index: false, follow: false },
};

const css = `
.navrh1{
    --blue:#0b4ea2;
    --red:#c8102e;
    --ink:#1a2233;
    --muted:#5b6578;
    --bg:#f6f8fc;
  }
.navrh1 *{box-sizing:border-box;}
.navrh1{
    margin:0;
    font-family:"Segoe UI", Arial, sans-serif;
    background:var(--bg);
    color:var(--ink);
  }
.navrh1 .shell{max-width:1200px;margin:0 auto;padding:22px 24px 60px;}
.navrh1 /* -- Header -- */
  .tricolor{height:4px;display:flex;}
.navrh1 .tricolor span{flex:1;}
.navrh1 .tricolor .w{background:#fff;}
.navrh1 .tricolor .b{background:var(--blue);}
.navrh1 .tricolor .r{background:var(--red);}
.navrh1 header{
    display:flex;align-items:center;justify-content:space-between;
    padding:18px 0;
  }
.navrh1 .logo{display:flex;align-items:center;gap:10px;}
.navrh1 .logo-mark{
    width:38px;height:38px;border-radius:10px;
    background:var(--blue);
    display:grid;place-items:center;
    color:#fff;font-weight:800;font-size:1.05rem;
    position:relative;
  }
.navrh1 .logo-mark::after{
    content:"";position:absolute;right:-2px;bottom:-2px;
    width:10px;height:10px;border-radius:50%;background:var(--red);
    border:2px solid var(--bg);
  }
.navrh1 .logo-text{font-weight:800;font-size:1.25rem;letter-spacing:-0.02em;color:var(--ink);}
.navrh1 nav{display:flex;gap:26px;}
.navrh1 nav a{color:var(--muted);text-decoration:none;font-size:0.92rem;font-weight:600;}
.navrh1 nav a:hover{color:var(--blue);}
.navrh1 .cta{
    background:var(--blue);color:#fff;border:none;padding:10px 18px;
    border-radius:10px;font-weight:700;font-size:0.9rem;cursor:pointer;
  }
.navrh1 /* -- Hero -- */
  .hero{
    position:relative;
    margin-top:30px;
    padding:60px 10px 110px;
    text-align:center;
    overflow:hidden;
    border-radius:28px;
    background:linear-gradient(180deg,#eef3fb 0%, #e3ecf9 100%);
  }
.navrh1 .hero-eyebrow{
    display:inline-flex;align-items:center;gap:8px;
    padding:6px 14px;border-radius:999px;
    background:rgba(11,78,162,0.08);color:var(--blue);
    font-size:0.78rem;font-weight:700;letter-spacing:0.04em;text-transform:uppercase;
  }
.navrh1 .hero h1{
    margin:22px auto 14px;max-width:780px;
    font-size:3.1rem;line-height:1.08;letter-spacing:-0.03em;font-weight:800;
  }
.navrh1 .hero h1 em{font-style:normal;color:var(--blue);}
.navrh1 .hero p{max-width:560px;margin:0 auto;color:var(--muted);font-size:1.08rem;line-height:1.6;}
.navrh1 .search{
    max-width:640px;margin:30px auto 0;
    display:flex;gap:8px;padding:8px;
    background:#fff;border-radius:16px;
    box-shadow:0 20px 40px rgba(16,30,60,0.12);
    border:1px solid #e4e9f3;
  }
.navrh1 .search input{
    flex:1;border:none;outline:none;padding:12px 14px;font-size:1rem;border-radius:10px;
  }
.navrh1 .search button{
    background:var(--red);color:#fff;border:none;padding:12px 22px;border-radius:10px;font-weight:700;cursor:pointer;
  }
.navrh1 /* mountain silhouette */
  .mountains{
    position:absolute;left:0;right:0;bottom:0;height:140px;
  }
.navrh1 .mountains svg{width:100%;height:100%;display:block;}
.navrh1 /* -- Today strip (replaces the big blue box) -- */
  .today-strip{
    display:grid;grid-template-columns:repeat(4,1fr);
    gap:14px;margin-top:-56px;position:relative;z-index:2;
  }
.navrh1 .today-card{
    background:#fff;border-radius:16px;padding:16px 18px;
    box-shadow:0 14px 32px rgba(16,30,60,0.08);border:1px solid #edf1f8;
  }
.navrh1 .today-card span{display:block;color:var(--muted);font-size:0.72rem;font-weight:700;text-transform:uppercase;letter-spacing:0.04em;margin-bottom:6px;}
.navrh1 .today-card strong{font-size:1.35rem;}
.navrh1 .today-card small{display:block;color:var(--muted);font-size:0.78rem;margin-top:4px;}
.navrh1 /* -- content sections -- */
  .grid2{display:grid;grid-template-columns:1.2fr 1fr;gap:20px;margin-top:56px;}
.navrh1 .card{
    background:#fff;border-radius:20px;padding:22px;
    border:1px solid #edf1f8;box-shadow:0 10px 24px rgba(16,30,60,0.05);
  }
.navrh1 .card h3{margin:0 0 10px;font-size:1.1rem;}
.navrh1 .card p{margin:0;color:var(--muted);font-size:0.9rem;line-height:1.6;}
.navrh1 .note{text-align:center;margin-top:50px;color:var(--muted);font-size:0.85rem;}
.navrh1 .note b{color:var(--ink);}
`;

const bodyHtml = `<div class="tricolor"><span class="w"></span><span class="b"></span><span class="r"></span></div>
<div class="shell">
  <header>
    <div class="logo">
      <div class="logo-mark">Q4</div>
      <div class="logo-text">Q4.sk</div>
    </div>
    <nav>
      <a href="#">Počasie</a>
      <a href="#">Sviatky</a>
      <a href="#">Štatistiky</a>
      <a href="#">Naživo</a>
      <a href="#">Obce</a>
      <a href="#">Kalkulačky</a>
    </nav>
    <button class="cta">Vyhľadať firmu</button>
  </header>

  <section class="hero">
    <span class="hero-eyebrow">● Slovensko v jednom prehľade</span>
    <h1>Všetko dôležité <em>o Slovensku</em>,<br/>prehľadne na jednom mieste.</h1>
    <p>Počasie, sviatky, kurzy, štatistiky a overené údaje o firmách — bez zbytočného balastu.</p>
    <div class="search">
      <input placeholder="Hľadať firmu, obec alebo IČO…" />
      <button>Hľadať</button>
    </div>
    <div class="mountains">
      <svg viewBox="0 0 1200 160" preserveAspectRatio="none">
        <polygon points="0,160 0,95 120,40 230,100 330,55 420,110 520,30 640,100 760,60 860,115 980,50 1100,100 1200,70 1200,160" fill="#0b4ea2" opacity="0.1"/>
        <polygon points="0,160 0,120 150,70 260,120 380,85 500,130 620,65 740,120 880,90 1000,135 1120,95 1200,120 1200,160" fill="#0b4ea2" opacity="0.18"/>
      </svg>
    </div>
  </section>

  <div class="today-strip">
    <div class="today-card"><span>Počasie teraz</span><strong>14°C</strong><small>Bratislava · polooblačno</small></div>
    <div class="today-card"><span>Meniny má</span><strong>Igor</strong><small>zajtra: Edita</small></div>
    <div class="today-card"><span>Kurz EUR/USD</span><strong>1,083</strong><small>+0,12 % dnes</small></div>
    <div class="today-card"><span>Štátny dlh SR</span><strong>92,0 mld €</strong><small>rastie ~187 €/s</small></div>
  </div>

  <div class="grid2">
    <div class="card">
      <h3>Správy a články</h3>
      <p>Ekonomika a podnikanie na Slovensku — výber najdôležitejších článkov dňa.</p>
    </div>
    <div class="card">
      <h3>Najbližšie udalosti</h3>
      <p>Voľby, sviatky a prázdniny — vieš presne, čo ťa čaká najbližšie.</p>
    </div>
  </div>

  <p class="note">Návrh č. 1 — <b>„Tatranský horizont“</b>: svetlý, čistý dizajn s jemnou siluetou hôr, bez veľkého tmavého boxu.</p>
</div>`;

export default function Page() {
  return (
    <div className="navrh1">
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <div dangerouslySetInnerHTML={{ __html: bodyHtml }} />
    </div>
  );
}
