import type { Metadata } from "next";

// Static visual mockup — not linked from navigation, excluded from indexing.
// Generated by scripts/build-design-mockups.mjs from design-mockups/navrh-3-tmavy-glass.html.
export const metadata: Metadata = {
  title: "Návrh 3 – Tmavý alpský glass | Q4.sk návrh",
  robots: { index: false, follow: false },
};

const css = `
.navrh3{
    --blue:#3f7ae0;
    --red:#e24d5a;
    --ink:#0d1320;
    --muted:#9aa6c0;
  }
.navrh3 *{box-sizing:border-box;}
.navrh3{
    margin:0;font-family:"Segoe UI",Arial,sans-serif;color:#eef2fb;
    background:
      radial-gradient(circle at 15% 0%, rgba(63,122,224,0.35), transparent 45%),
      radial-gradient(circle at 85% 10%, rgba(226,77,90,0.22), transparent 40%),
      radial-gradient(circle at 50% 100%, rgba(63,122,224,0.18), transparent 50%),
      var(--ink);
    min-height:100vh;
  }
.navrh3 .shell{max-width:1200px;margin:0 auto;padding:22px 24px 70px;}
.navrh3 header{display:flex;align-items:center;justify-content:space-between;padding:10px 4px;}
.navrh3 .logo{display:flex;align-items:center;gap:10px;}
.navrh3 .logo-mark{
    width:14px;height:14px;transform:rotate(45deg);
    background:linear-gradient(135deg,var(--blue),var(--red));
    border-radius:4px;
  }
.navrh3 .logo-text{font-weight:700;font-size:1.1rem;letter-spacing:0.01em;color:#fff;}
.navrh3 .logo-text b{font-weight:800;}
.navrh3 nav{display:flex;gap:28px;}
.navrh3 nav a{color:var(--muted);text-decoration:none;font-size:0.88rem;font-weight:600;padding-bottom:4px;border-bottom:2px solid transparent;}
.navrh3 nav a:hover{color:#fff;border-color:var(--blue);}
.navrh3 .cta{
    background:rgba(255,255,255,0.08);color:#fff;border:1px solid rgba(255,255,255,0.18);
    padding:9px 16px;border-radius:999px;font-weight:600;font-size:0.84rem;cursor:pointer;
    backdrop-filter:blur(8px);
  }
.navrh3 .hero{
    margin-top:36px;text-align:center;padding:30px 10px 10px;
  }
.navrh3 .hero .kicker{
    display:inline-flex;align-items:center;gap:8px;color:#cfe0ff;
    background:rgba(63,122,224,0.14);border:1px solid rgba(63,122,224,0.3);
    padding:7px 14px;border-radius:999px;font-size:0.76rem;font-weight:700;letter-spacing:0.05em;text-transform:uppercase;
  }
.navrh3 .hero h1{
    font-size:3.4rem;line-height:1.04;letter-spacing:-0.035em;margin:24px auto 14px;max-width:820px;font-weight:800;
  }
.navrh3 .hero h1 span{
    background:linear-gradient(90deg,var(--blue),var(--red));
    -webkit-background-clip:text;background-clip:text;color:transparent;
  }
.navrh3 .hero p{max-width:560px;margin:0 auto;color:var(--muted);font-size:1.05rem;line-height:1.6;}
.navrh3 .search{
    max-width:620px;margin:28px auto 0;display:flex;gap:8px;padding:8px;
    background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.14);
    border-radius:18px;backdrop-filter:blur(16px);
  }
.navrh3 .search input{
    flex:1;background:transparent;border:none;outline:none;color:#fff;padding:12px 14px;font-size:1rem;
  }
.navrh3 .search input::placeholder{color:var(--muted);}
.navrh3 .search button{
    background:linear-gradient(135deg,var(--blue),#2a5bc0);color:#fff;border:none;padding:12px 22px;
    border-radius:12px;font-weight:700;cursor:pointer;
  }
.navrh3 .glass-row{
    margin-top:50px;display:grid;grid-template-columns:repeat(4,1fr);gap:14px;
  }
.navrh3 .glass-card{
    background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.12);
    border-radius:18px;padding:18px;backdrop-filter:blur(14px);
  }
.navrh3 .glass-card span{display:block;color:var(--muted);font-size:0.7rem;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8px;}
.navrh3 .glass-card strong{font-size:1.4rem;color:#fff;}
.navrh3 .glass-card small{display:block;color:var(--muted);font-size:0.76rem;margin-top:4px;}
.navrh3 .two-col{display:grid;grid-template-columns:1.2fr 1fr;gap:18px;margin-top:50px;}
.navrh3 .panel{
    background:rgba(255,255,255,0.045);border:1px solid rgba(255,255,255,0.1);
    border-radius:20px;padding:22px;backdrop-filter:blur(14px);
  }
.navrh3 .panel h3{margin:0 0 10px;color:#fff;font-size:1.05rem;}
.navrh3 .panel p{margin:0;color:var(--muted);font-size:0.88rem;line-height:1.6;}
.navrh3 .note{text-align:center;margin-top:50px;color:var(--muted);font-size:0.85rem;}
.navrh3 .note b{color:#fff;}
`;

const bodyHtml = `<div class="shell">
  <header>
    <div class="logo">
      <div class="logo-mark"></div>
      <div class="logo-text">Q4<b>.sk</b></div>
    </div>
    <nav>
      <a href="#">Počasie</a>
      <a href="#">Sviatky</a>
      <a href="#">Štatistiky</a>
      <a href="#">Naživo</a>
      <a href="#">Obce</a>
      <a href="#">Kalkulačky</a>
    </nav>
    <button class="cta">Vyhľadať firmu</button>
  </header>

  <section class="hero">
    <span class="kicker">● Slovensko v reálnom čase</span>
    <h1>Slovensko <span>naživo</span>,<br/>prehľadne na jednom mieste.</h1>
    <p>Počasie, sviatky, kurzy a overené dáta o firmách — jemný, moderný prehľad bez zbytočného šumu.</p>
    <div class="search">
      <input placeholder="Hľadať firmu, obec alebo IČO…" />
      <button>Hľadať</button>
    </div>
  </section>

  <div class="glass-row">
    <div class="glass-card"><span>Počasie teraz</span><strong>14°C</strong><small>Bratislava · polooblačno</small></div>
    <div class="glass-card"><span>Meniny má</span><strong>Igor</strong><small>zajtra: Edita</small></div>
    <div class="glass-card"><span>Kurz EUR/USD</span><strong>1,083</strong><small>+0,12 % dnes</small></div>
    <div class="glass-card"><span>Štátny dlh SR</span><strong>92,0 mld €</strong><small>rastie ~187 €/s</small></div>
  </div>

  <div class="two-col">
    <div class="panel">
      <h3>Správy a články</h3>
      <p>Ekonomika a podnikanie na Slovensku — prehľadný výber článkov dňa v jednoduchom zozname.</p>
    </div>
    <div class="panel">
      <h3>Najbližšie udalosti</h3>
      <p>Voľby, sviatky a prázdniny — vždy vieš, čo príde ďalej.</p>
    </div>
  </div>

  <p class="note">Návrh č. 3 — <b>„Tmavý alpský glass“</b>: tmavé pozadie s jemnou modro-červenou žiarou namiesto plného modrého boxu, sklené karty.</p>
</div>`;

export default function Page() {
  return (
    <div className="navrh3">
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <div dangerouslySetInnerHTML={{ __html: bodyHtml }} />
    </div>
  );
}
